// <auto-generated />
namespace Kadry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changes_in_person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_in_person));
        
        string IMigrationMetadata.Id
        {
            get { return "202202081543434_changes_in_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
